version: '3'

services: 
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports: 
      - 80:80
    volumes: 
      - static_volume:/backend/static
      - ./docker/nginx/development:/etc/nginx/conf.d
    depends_on:
      - backend
  backend: &backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - static_volume:/backend/static
    ports:
      - 8000:8000
    depends_on: 
      - db
      - redis
    command: >
      sh -c "python manage.py wait_for_db"
    env_file:
      - ./backend/.env
    networks:
      - djangonetwork
  db:
    image: postgres:13.1-alpine
    env_file:
      - ./backend/.env
    networks:
      - djangonetwork

  redis:
    image: redis:alpine
    ports: 
      - "6379:6379"
    networks:
      - djangonetwork
  
  celery_app:
    <<: *backend
    ports:
      - 8001:8001
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
    

volumes:
  static_volume: {}

networks:
  djangonetwork:
    driver: bridge